### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by PapsOu** [neild3r/vscode-php-docblocker#195]
Hello, under VSCode 1.60.1 , the extension does not work anymore.

Please find the output stack trace : 
```
[2021-09-17 10:24:02.257] [renderer1] [error] Cannot read property '2' of null: TypeError: Cannot read property '2' of null
    at C.parse (/home/papsou/.vscode/extensions/neilbrayfield.php-docblocker-2.4.0/out/src/extension.js:6:2028)
    at T.autoDocument (/home/papsou/.vscode/extensions/neilbrayfield.php-docblocker-2.4.0/out/src/extension.js:6:4007)
    at _.provideCompletionItems (/home/papsou/.vscode/extensions/neilbrayfield.php-docblocker-2.4.0/out/src/extension.js:6:7730)
    at $.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:176938)
    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:197582
    at xe._withAdapter (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:187656)
    at xe.$provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:197558)
    at i._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13543)
    at i._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13227)
    at i._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:11838)
    at i._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10567)
    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8663
    at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30187
    at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
    at r._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21051)
    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:17929
    at c.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at v.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13142)
    at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12490
    at Socket.w (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13350)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Detailed informations : 

```
PHP DocBlocker: v2.4.0

global config : 

{
    "php-docblocker.returnGap": true,
    "php-docblocker.useShortNames": true,
}
```

```
Version : 1.60.1
Commit : 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date : 2021-09-10T17:06:57.931Z
Electron : 13.1.8
Chrome : 91.0.4472.164
Node.js : 14.16.0
V8 : 9.1.269.39-electron.0
OS : Linux x64 5.13.14-200.fc34.x86_64
```

**Comment by PapsOu** [comment]
The error happens only when the method to document has an error : 

```php
    /** <- no completion
    public function __construct(
        Swift_Mailer $mailer, // the comma is triggering an error
    ) {
```

```php
    /** <- completion is ok
    public function __construct(
        Swift_Mailer $mailer
    ) {
```

So the extension is working well in standard cases.

May be it is possible to display a tooltip indicating that the method need to be fixed before generating the docblock ?

**Comment by neild3r** [comment]
Trailing comma should be supported now so not sure why this isn't working
