### ISSUE TITLE
Doesn't work anymore ?

### ISSUE THREAD

**Issue by momala454** [neild3r/vscode-php-docblocker#208]
Nothing is autofilled and the extension is installed on ssh

![image](https://user-images.githubusercontent.com/83005/136525502-5439d48e-9940-49d9-8341-5797d3a5efac.png)

![image](https://user-images.githubusercontent.com/83005/136525532-b7f0b0cb-f075-4489-a6b9-15161b77d31a.png)

![image](https://user-images.githubusercontent.com/83005/136525561-6039bd78-14bd-4b70-96d9-49af0678684c.png)

**Comment by neild3r** [comment]
Replicated, this is the stack trace. Seems to be related to the fetching of the class head which is designed to help with reading class use statements

```
[2021-10-08 11:06:05.098] [exthost] [error] TypeError: Cannot read property 'index' of null
	at N.getClassHead (/Users/neil/.vscode/extensions/neilbrayfield.php-docblocker-2.6.0/out/src/extension.js:1:2358)
	at N.parse (/Users/neil/.vscode/extensions/neilbrayfield.php-docblocker-2.6.0/out/src/extension.js:6:2777)
	at w.autoDocument (/Users/neil/.vscode/extensions/neilbrayfield.php-docblocker-2.6.0/out/src/extension.js:6:4956)
	at E.provideCompletionItems (/Users/neil/.vscode/extensions/neilbrayfield.php-docblocker-2.6.0/out/src/extension.js:6:11554)
	at $.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:176938)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:197582
	at xe._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:187656)
	at xe.$provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:197558)
	at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13543)
	at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13227)
	at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:11838)
	at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10567)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8663
	at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30187
	at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
	at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21051)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:17929
	at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13142)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12490
	at Socket.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13350)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```
